version: "3.8"

services:
  ml-backend:
    container_name: ml-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TEST_ENV: ${TEST_ENV}
    environment:
      # Basic authentication for the model server
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
      # Set the log level for the model server
      - LOG_LEVEL=DEBUG
      # Additional parameters for the model server
      - ANY=PARAMETER
      # Specify the number of workers and threads for the model server
      - WORKERS=1
      - THREADS=8
      # Define the model directory
      - MODEL_DIR=/data/models

      # Label Studio configuration
      - LABEL_STUDIO_URL=http://localhost:8080
      - LABEL_STUDIO_API_KEY=trucxinh
      - BASELINE_MODEL_NAME=auto-labeling

    ports:
      - "9090:9090"
    volumes:
      - "./data/server:/data"
      # - "./cifar10:/app/panda/cifar10" 
      - "./correction:/app/panda/correction"
      - "./data_processing:/app/panda/data_processing"
      - "./detection:/app/panda/detection"
      - "./labeling:/app/panda/labeling"
